id: TestAdminPlaybook
name: TestAdminPlaybook
version: -1
fromversion: 4.5.0
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: '0'
    type: start
    task:
      id: '0'
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: '{"position":{"x":50,"y":50}}'
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: 1
    taskid: '1'
    type: regular
    task:
      id: '1'
      version: -1
      name: DeleteContext
      description: ''
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: yes
    separatecontext: false
    view: '{"position":{"x":50,"y":200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '2':
    id: 2
    taskid: '2'
    type: regular
    task:
      id: '2'
      version: -1
      name: darktrace-run-advanced-search-analysis
      description: ''
      script: DarktraceAdmin|||darktrace-run-advanced-search-analysis
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '3':
    id: '3'
    taskid: '3'
    type: condition
    task:
      id: '3'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '4'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.AdvancedSearch
            iscontext: true
    view: '{"position":{"x":50,"y":600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '4':
    id: 4
    taskid: '4'
    type: regular
    task:
      id: '4'
      version: -1
      name: darktrace-get-device-connection-info
      description: ''
      script: DarktraceAdmin|||darktrace-get-device-connection-info
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '5'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '5':
    id: '5'
    taskid: '5'
    type: condition
    task:
      id: '5'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '6'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.DeviceConnectionInfo
            iscontext: true
    view: '{"position":{"x":50,"y":1000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '6':
    id: 6
    taskid: '6'
    type: regular
    task:
      id: '6'
      version: -1
      name: darktrace-get-external-endpoint-details
      description: ''
      script: DarktraceAdmin|||darktrace-get-external-endpoint-details
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '7'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":1200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '7':
    id: '7'
    taskid: '7'
    type: condition
    task:
      id: '7'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '8'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.ExternalEndpointDetails
            iscontext: true
    view: '{"position":{"x":50,"y":1400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '8':
    id: 8
    taskid: '8'
    type: regular
    task:
      id: '8'
      version: -1
      name: darktrace-get-similar-devices
      description: ''
      script: DarktraceAdmin|||darktrace-get-similar-devices
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '9'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":1600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '9':
    id: '9'
    taskid: '9'
    type: condition
    task:
      id: '9'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '10'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.SimilarDevices.deviceId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.SimilarDevices.devices
            iscontext: true
    view: '{"position":{"x":50,"y":1800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '10':
    id: 10
    taskid: '10'
    type: regular
    task:
      id: '10'
      version: -1
      name: darktrace-post-to-watched-list
      description: ''
      script: DarktraceAdmin|||darktrace-post-to-watched-list
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '11'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":2000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '11':
    id: '11'
    taskid: '11'
    type: condition
    task:
      id: '11'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '12'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Endpoint.Watched
            iscontext: true
    view: '{"position":{"x":50,"y":2200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '12':
    id: 12
    taskid: '12'
    type: regular
    task:
      id: '12'
      version: -1
      name: darktrace-get-tagged-devices
      description: ''
      script: DarktraceAdmin|||darktrace-get-tagged-devices
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '13'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":2400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '13':
    id: '13'
    taskid: '13'
    type: condition
    task:
      id: '13'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '14'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.deviceId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.hostname
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.label
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.credentials
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.otherTags
            iscontext: true
    view: '{"position":{"x":50,"y":2600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '14':
    id: 14
    taskid: '14'
    type: regular
    task:
      id: '14'
      version: -1
      name: darktrace-get-tags-for-device
      description: ''
      script: DarktraceAdmin|||darktrace-get-tags-for-device
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '15'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":2800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '15':
    id: '15'
    taskid: '15'
    type: condition
    task:
      id: '15'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '16'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.tagId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.tagName
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.tagDescription
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.expiry
            iscontext: true
    view: '{"position":{"x":50,"y":3000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '16':
    id: 16
    taskid: '16'
    type: regular
    task:
      id: '16'
      version: -1
      name: darktrace-post-tag-to-device
      description: ''
      script: DarktraceAdmin|||darktrace-post-tag-to-device
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '17'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":3200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '17':
    id: '17'
    taskid: '17'
    type: condition
    task:
      id: '17'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '18'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.tagId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.tagName
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.deviceId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Darktrace.Device.response
            iscontext: true
    view: '{"position":{"x":50,"y":3400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '18':
    id: '18'
    taskid: '18'
    type: title
    task:
      id: '18'
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: '{"position":{"x":50,"y":3600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
view: '{"linkLabelsPosition":{},"paper":{"dimensions":{"height":200,"width":380,"x":50,"y":50}}}'
inputs: []
outputs: []
